# Generated by Django 4.2.9 on 2024-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_quizdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScamSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('text_length', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'scam_sms',
            },
        ),
        migrations.DeleteModel(
            name='QuizData',
        ),
    ]
