# Generated by Django 4.2.9 on 2024-08-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_scamsms_delete_quizdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='scamsms',
            options={'managed': False},
        ),
    ]
