import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/navbar/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <div className="flex flex-col gap-16 w-full">
            <main className="flex min-h-screen w-full gap-y-16 flex-col items-center justify-between mx-auto py-24 md:p-24">
                {children}
            </main>
        </div>
    )
}
