import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar/NavBar'
import Footer from '@/components/footer/footer-four'
import Top from '@/components/top/top'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <head>
                <meta
                    http-equiv="Content-Security-Policy"
                    content="upgrade-insecure-requests"
                />
            </head>
            <body className={inter.className}>
                <NavBar />
                <main className="flex min-h-screen flex-col items-center justify-between p-24">
                    {children}
                </main>
                <Footer />
                <Top />
            </body>
        </html>
    )
}
