import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar/NavBar'
import Footer from '@/components/footer/footer-four'
import Top from '@/components/top/top'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <head>
                <meta
                    http-equiv="Content-Security-Policy"
                    content="upgrade-insecure-requests"
                />
            </head>
            <body className={cn(inter.className, 'w-full')}>
                <NavBar />
                <main className="flex flex-col items-center justify-between sm:px-8 md:px-24">
                    {children}
                </main>
                <Footer />
                <Top />
            </body>
        </html>
    )
}
